### ISSUE TITLE
Issues encountered with the latest version

### ISSUE THREAD

**Issue by parthadeka** [ARDG-NRAO/plumber#11]
As the Plumber-data repository is updated now, I tried installing the recent version of Plumber by cloning the Git repository to a local area and then performing "python setup.py install". The installation reports no error, but when I run it, e.g., parang_finder on an MS to find the parallactic angles, it returns angle values which are completely different from what was returned by the older version of Plumber. In addition, the telescope name is now returned as 'M', whereas earlier it used to be 'MeerKAT'. The position of the telescope is also now different from the stored value in the MS which we checked using msmd() task in CASA. Earlier this position value was reported to be the same as in the MS. Here are some screenshots of running older vs newer version of Plumber on an MS. First image is from running the older version, whereas second one is from the newer version.
![older_version_parang_finder](https://user-images.githubusercontent.com/59552517/158370249-7ae58d0c-e55c-4621-b2fb-343954512867.png)
![new_version_parang_finder](https://user-images.githubusercontent.com/59552517/158370252-c1f9c0a5-d8f2-4bd7-9819-2c77ca9c84f1.png)

**Comment by preshanth** [comment]
So it looks like a case of 2pi change in the parallactic angle value. This is simply a convention change to match the value that CASA throws internally. So the beam should not be different at all. Can you compare the beams generated by both these methods.

**Comment by Kitchi** [comment]
Thanks @parthadeka. The latest commit to `master` should fix these issues. They were errors in the logging, not in the actual computation of anything, so the functionality would have been unaffected.
