### ISSUE TITLE
AttributeError: StokesSpectralCube has no attribute stokes_data

### ISSUE THREAD

**Issue by o-smirnov** [ARDG-NRAO/plumber#18]
Crashes here: https://github.com/ARDG-NRAO/plumber/blob/master/plumber/image.py#L46

I think it needs to be ``_stokes_data`` i.e. with leading underscore.

**Comment by Kitchi** [comment]
Thanks for the raising issue @o-smirnov. You'll need to clone the current master branch of spectral cube (https://github.com/radio-astro-tools/spectral-cube), where this syntax exists. It hasn't made it to the `pip` installable version yet unfortunately. 

I'm working on a fix to our install scripts that will pull from the git branch directly for `spectral-cube` so this problem should go away soon.

**Comment by preshanth** [comment]
Should hopefully be in the next issue of `spectral_cube`
